http:
  routers:
    stacker:
      rule: "Host(`__STACKER_HOST__`)"
      entryPoints:
        - websecure
      service: stacker
      tls:
        certResolver: letsencrypt
  services:
    stacker:
      loadBalancer:
        servers:
          - url: http://stacker:8080
